- name: Comment out PermitRootLogin
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: '#PermitRootLogin'
    state: present
    
- name: Disallow root SSH access
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#PermitRootLogin'
    line: 'PermitRootLogin no'
    state: present

- name: Comment out PermitRootLogin
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: '#PermitRootLogin'
    state: present

- name: Enable PasswordAuthentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#PasswordAuthentication'
    line: 'PasswordAuthentication yes'
    state: present
