- block:
  - name: Source .bashrc
    shell: source ~/.bashrc
    args:
      executable: /bin/bash
    check_mode: no
    changed_when: no
    when: 'ansible_env.SHELL == "/bin/bash"'

  - debug:
      msg: "If next task fail, you should write some lines in order to load anyenv in your SHELL's configuration files and reload your shell to enable anyenv."
    when: 'ansible_env.SHELL != "/bin/bash"'

  - name: Install pyenv
    shell: anyenv install pyenv
    args:
      creates: "{{ ansible_env.HOME }}/.anyenv/envs/pyenv/bin/pyenv"

  - name: Install pyenv-virtualenv
    git:
      repo: https://github.com/yyuu/pyenv-virtualenv.git
      dest: "{{ ansible_env.HOME }}/.anyenv/envs/pyenv/plugins/pyenv-virtualenv"
      version: master

  tags: pyenv_install

- block:
  - include_tasks: macos.yml
    when: ansible_os_family == 'Darwin'

  - include_tasks: ubuntu.yml
    when: ansible_os_family == 'Debian'

  tags: python_install

