- name: Install dependencies
  apt:
    name: "{{ item }}"
  with_items:
    - make
    - build-essential
    - libssl-dev
    - zlib1g-dev
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev
    - wget
    - curl
    - llvm
    - libncurses5-dev
    - libncursesw5-dev
    - xz-utils
    - tk-dev
    - libffi-dev
  become: yes

- name: Install python
  shell: pyenv install '{{ item.version }}'
  args:
    creates: '~/.anyenv/envs/pyenv/versions/{{ item.version }}'
  with_items:
    - '{{ python_versions }}'
  when: python_versions is defined
  notify:
    - pyenv_rehash
